# Generated by Django 5.1.15 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='Filled with simulated students (manage.py simulate_class), not real ones.'),
        ),
    ]
