# Generated by Django 5.1.15 on 2026-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_simulated_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_answer',
            field=models.TextField(blank=True, help_text='A model answer, used to suggest scores for written answers.'),
        ),
        migrations.AddField(
            model_name='response',
            name='suggested_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
