# Generated by Django 5.1.15 on 2026-09-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_essay_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('text_hash', models.CharField(max_length=64)),
                ('vector', models.BinaryField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='bank.question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('keywords', models.JSONField(default=list)),
                ('size', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='bank.course')),
            ],
            options={
                'ordering': ['-size', 'label'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='bank.topic'),
        ),
    ]
